services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ebook_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: ebook_nginx
    restart: always
    ports:
      - "8001:81"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: ebook_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ebook_db
      MYSQL_USER: ebook_user
      MYSQL_PASSWORD: secret
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
